Repository codeit-sprint-fullstack/9-sprint-mission-fe, pull requests merged in 2025-08, with the labels that each got.

#18 [박성훈] Sprint 9
  README.md
  [backup]README.md
  index.html
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/icons/btn_visibility_off_24px.svg
  src/assets/icons/google_icon@3x.png
  src/assets/icons/ic_facebook@3x.png
  src/assets/icons/ic_instagram@3x.png
  src/assets/icons/ic_twitter@3x.png
  src/assets/icons/ic_youtube@3x.png
  src/assets/icons/katalk_icon@3x.png
  src/assets/images/landing/Img_home_01.png
  src/assets/images/landing/Img_home_02.png
  src/assets/images/landing/Img_home_03.png
  src/assets/images/landing/Img_home_bottom.png
  src/assets/images/landing/Img_home_top.png
  src/assets/images/panda-market.png
  src/htmls/login.html
  src/htmls/signup.html
  src/styles/reset.css
  src/styles/style-login.css
  src/styles/style-signup.css
  src/styles/style.css
Labels: 매운맛🔥

#1 Basic 백수현 스프린트 미션 1 & 2 제출
  .github/README.md
  .github/pull-request-template.md
  faq.html
  img/Img_home_01.svg
  img/Img_home_02.svg
  img/Img_home_03.svg
  img/Img_home_bottom.svg
  img/Img_home_top.svg
  img/btn_visibility_off.svg
  img/btn_visibility_on.svg
  img/ic_facebook.svg
  img/ic_instagram.svg
  img/ic_twitter.svg
  img/ic_youtube.svg
  img/img_face_panda.svg
  img/login_google.svg
  img/login_kakao.svg
  img/login_logo.svg
  img/typo.svg
  index.js
  items.html
  landing.html
  login.html
  privacy.html
  reset.css
  signup.html
  style.css
  workflows/auto-label-assign.yml
Labels: 진행 중 🏃

#16 Basic 김명진 sprint1
  README.md
  img/Component 2.png
  img/Component 3.png
  img/Img_home_01.png
  img/Img_home_01@2x.png
  img/Img_home_01@3x.png
  img/Img_home_02-1.png
  img/Img_home_02.png
  img/Img_home_02@2x.png
  img/Img_home_03.png
  img/Img_home_03@2x.png
  img/Img_home_03@3x.png
  img/Img_home_bottom.png
  img/Img_home_bottom@2x.png
  img/Img_home_bottom@3x.png
  img/Img_home_top.png
  img/Property 1=Typo.png
  img/Property 1=Typo@2x.png
  img/Property 1=Typo@3x.png
  img/btn_visibility_off_24px.svg
  img/face.svg
  img/insta.svg
  img/panda.png
  img/panda.svg
  img/twitter.svg
  img/youtube.svg
  index.html
  reset.css
  style.css
Labels: 매운맛🔥, 최종 제출

#21 Basic 오마린 스프린트 미션 1,2 제출
  faq.html
  global.css
  images/panda1.png
  images/panda2.png
  images/panda3.png
  images/panda4.png
  images/panda5.png
  images/pandalogo.png
  index.html
  items.html
  login.html
  privacy.html
  reset.css
  signup.html
Labels: 진행 중 🏃
