Repository codeit-sprint-fullstack/9-sprint-mission-fe, pull requests merged in 2025-09, with the labels that each got.

#27 Basic 오마린 스프린트 미션 3 제출
  global.css
  images/facebook.png
  images/insta.png
  images/tw.png
  images/youtube.png
  index.html
  login.html
  modal.js
  reset.css
  signup.html
  validation.js
Labels: 순한맛🐑

#35 Basic 박성훈 스프린트 미션 3 제출
  [backup]README.md
  index.html
  src/htmls/login.html
  src/htmls/signup.html
  src/scripts/login.mjs
  src/scripts/script-common.mjs
  src/scripts/signup.mjs
  src/styles/style-common.css
  src/styles/style-signup.css
  style.css
Labels: 매운맛🔥, 미완성🫠

#30 Basic 이유리 스프린트 미션 3 제출
  assets/icon/btn_visibility_on.svg
  assets/logo/og_title.png
  assets/screenshots/og-tag-ex.png
  data/userdata.js
  index.html
  pages/faq.html
  pages/items.html
  pages/login.html
  pages/privacy.html
  pages/signup.html
  script/alert-modal.js
  script/login.js
  script/signup.js
  script/validation.js
  script/visibility.js
  styles/auth.css
  styles/index.css
  styles/theme.css
Labels: 매운맛🔥

#43 Basic 이유리 스프린트 미션 4 제출
  .gitignore
  README.md
  package-lock.json
  package.json
  src/api/ArticleService.js
  src/api/ProductService.js
  src/assets/icon/btn_visibility_off.svg
  src/assets/icon/btn_visibility_on.svg
  src/assets/icon/ic_facebook.png
  src/assets/icon/ic_google.png
  src/assets/icon/ic_instagram.png
  src/assets/icon/ic_kakaotalk.png
  src/assets/icon/ic_twitter.png
  src/assets/icon/ic_youtube.png
  src/assets/img/img_home_01.png
  src/assets/img/img_home_02.png
  src/assets/img/img_home_03.png
  src/assets/img/img_home_bottom.png
  src/assets/img/img_home_top.png
  src/assets/logo/favicon.ico
  src/assets/logo/logo_panda_face.png
  src/assets/logo/logo_panda_face_big.png
  src/assets/logo/og_title.png
  src/assets/screenshots/og-tag-ex.png
  src/data/userdata.js
  src/fonts/ROKAFSansMedium.woff2
  src/index.html
  src/pages/faq.html
  src/pages/items.html
  src/pages/login.html
  src/pages/privacy.html
  src/pages/signup.html
  src/script/alert-modal.js
  src/script/login.js
  src/script/main.js
  src/script/signup.js
  src/script/validation.js
  src/script/visibility.js
  src/styles/auth.css
  src/styles/index.css
  src/styles/reset.css
  src/styles/theme.css
Labels: 매운맛🔥
